### ISSUE TITLE
i have an issue with erroring, even if i changed everything

### ISSUE THREAD

**Issue by winmastti** [ultimate120/bedrock-crack#5]
![image](https://github.com/user-attachments/assets/693d1a0a-5704-49bf-b2b0-09971c328c62)

heeelp

**Comment by ahmedjacop68** [comment]
sign in to your microsoft account in the Store, and if that doesn't work just uninstall Minecraft and then install the free trial of Minecraft and then repeat all the steps again

**Comment by ultimate120** [comment]
Try to turn off clipSVC from taskmanger then download minecraft then try
