### ISSUE TITLE
What is TakeOwnershipPro

### ISSUE THREAD

**Issue by portex7000** [ultimate120/bedrock-crack#6]
![image](https://github.com/user-attachments/assets/babe8b64-b2f1-474f-9332-07cc777ccced)
This is not minecraft bedrock launcher

**Comment by ahmedjacop68** [comment]
are you a fucking idiot, this app is to take ownership of the system32 Folder and SysWOW64 folder

**Comment by portex7000** [comment]
> are you a fucking idiot, this app is to take ownership of the system32 Folder and SysWOW64 folder

This downloads when i download the launcher (don't worry it is on vm, i know to not download suspicious software)

**Comment by ultimate120** [comment]
This is not the minecraft launcher you have to download the launcher from somewhere else it is in the instructions. This helps you take ownership of system32 And 64 folders to add files there thanks if you have any questions open up a new issue
